-- Create products table and seed from existing menu
CREATE TABLE IF NOT EXISTS products (
  id serial PRIMARY KEY,
  category text NOT NULL,
  title text NOT NULL,
  description text,
  price numeric(10,2) NOT NULL DEFAULT 0,
  sold_by text,
  qty_label text,
  image_url text,
  active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

-- Add deleted flag to orders
ALTER TABLE orders ADD COLUMN IF NOT EXISTS is_deleted boolean DEFAULT false;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

-- Seed products based on the current Shabbos menu
INSERT INTO products (category,title,description,price,sold_by,qty_label,image_url,active) VALUES
('Salatim','Chummus','Smooth, velvety chickpea purée.',25.00,'250 ml','Order Qty','/assets/Shabbos/Chummus.jpg',true),
('Salatim','Techina','Silky sesame techina blended with garlic and lemon.',25.00,'250 ml','Order Qty','/assets/Shabbos/Techina.jpeg',true),
('Salatim','Coleslaw','Shredded cabbage and carrots in a light creamy dressing.',25.00,'250 ml','Order Qty','/assets/Shabbos/Coleslaw.jpg',true),
('Salatim','Beet Salad','Roasted beets with citrus and mint – earthy sweetness in every bite.',25.00,'250 ml','Order Qty','/assets/Shabbos/Beet Salad.jpg',true),
('Salatim','Purple Cabbage Salad','Vibrant shredded cabbage with tangy dressing and seeds — a visual and flavorful pop.',25.00,'250 ml','Order Qty','/assets/Shabbos/Purple Cabbage Salad.jpg',true),
('Salatim','Garlic Confit','Slow-roasted garlic cloves and leeks in oil.',25.00,'250 ml','Order Qty','/assets/Shabbos/Garlic Confit.webp',true),
('Salatim','Taboule','Finely chopped parsley, tomato, and bulgur.',25.00,'250 ml','Order Qty','/assets/Shabbos/Taboule.webp',true),
('Salatim','Roasted Peppers','Roasted red and yellow peppers with oil and sea salt.',25.00,'250 ml','Order Qty','/assets/Shabbos/Roasted Peppers.jpeg',true),
('Salatim','Onion Dip','Caramelized onions folded into creamy base.',25.00,'250 ml','Order Qty','/assets/Shabbos/Onion Dip.jpg',true),
('Salatim','Eggplant with Tehina','Charred eggplant mashed with tahini, lemon, and garlic.',25.00,'250 ml','Order Qty','/assets/Shabbos/Eggplant with Tehina.jpg',true),
('Salatim','Olive Dip','Chopped olives with herbs in a creamy base.',25.00,'250 ml','Order Qty','/assets/Shabbos/Olive Dip.jpg',true),
('Salatim','Marinated Mushrooms','Button mushrooms in herbed vinaigrette.',25.00,'250 ml','Order Qty','/assets/Shabbos/Marinated Mushrooms.jpeg',true),
('Salatim','Dill Apple Cabbage Salad','Crisp cabbage and apple with fresh dill.',25.00,'250 ml','Order Qty','/assets/Shabbos/Dill Apple Cabbage Salad.jpg',true),
('Salatim','Dill Dip','Creamy herb dip with fresh dill and lemon.',25.00,'250 ml','Order Qty','/assets/Shabbos/Dill Dip.jpeg',true),
('Appetizers','Meat Cigars','',300.00,'9x13 Pan','Order Qty','/assets/Shabbos/Meat Cigars.png',true),
('Fish','Maple Mustard Pecan Crust Salmon','Tender salmon fillet baked beneath a golden crust of toasted pecans, brushed with a maple–mustard glaze that''s equal parts sweet, nutty, and sophisticated.',300.00,'Side','Order Qty','/assets/Shabbos/pecan-crusted-salmon.jpg',true),
('Fish','Teriyaki Salmon','Succulent salmon marinated in our house teriyaki blend, kissed with soy, ginger, and sesame, then caramelized to perfection for a glossy, savory finish.',300.00,'Side','Order Qty','/assets/Shabbos/Teriyaki-Salmon.jpg',true),
('Fish','Moroccon Salmon','A vibrant North African favorite simmered in a rich tomato-pepper sauce with garlic, paprika, and a touch of spice that warms the soul.',300.00,'Side','Order Qty','/assets/Shabbos/Moroccan-Salmon.jpeg',true),
('Fish','Pesto Salmon','Pan-seared salmon coated in rustic basil pesto with roasted pine nuts and olive oil — bright, herby, and impossibly fresh.',300.00,'Side','Order Qty','/assets/Shabbos/Pesto-Salmon.jpg',true),
('Fish','Lemon Dill Salmon','Light and elegant — fresh lemon, aromatic dill, and a touch of olive oil bring out the clean flavor of perfectly baked salmon.',300.00,'Side','Order Qty','/assets/Shabbos/lemon-dill-salmon.jpg',true),
('Fish','Hickory Spiced Salmon Skewers','Smoky, char-grilled skewers of salmon seasoned with hickory and spice — bold, rustic, and ready for the table.',300.00,'Side','Order Qty','/assets/Shabbos/Hickory-Spiced-Salmon-Skewers.jpeg',true),
('Fish','Gefilte Fish','A classic with heart — handmade and gently poached, served with a hint of sweetness and traditional carrot garnish.',120.00,'Loaf','Order Qty','/assets/Shabbos/Gefilte-Fish.jpg',true),
('Soups','Chicken Soup','The essence of Shabbos comfort — slow-simmered broth rich with tender chicken, carrots, and dill.',50.00,'Litre','Order Qty','/assets/Shabbos/Chicken-Soup.jpg',true),
('Soups','Butternut Squash Soup','Velvety and naturally sweet, with roasted squash, cinnamon, and a drizzle of olive oil — a cozy bowl of autumn warmth.',45.00,'Litre','Order Qty','/assets/Shabbos/Butternut-Squash-Soup.jpg',true),
('Soups','Split Pea Soup','Hearty and homespun, simmered low and slow with onions, garlic, and a whisper of smoked flavor.',45.00,'Litre','Order Qty','/assets/Shabbos/Split Pea Soup.jpg',true),
('Soups','Vegetable Lentil Soup','A rustic medley of lentils, garden vegetables, and herbs — nourishing, earthy, and full of heart.',45.00,'Litre','Order Qty','/assets/Shabbos/Vegetable -lentil-soup.jpg',true),
('Soups','Potato Leek Soup','Creamy and comforting, with caramelized leeks and silky potatoes blended into pure coziness.',45.00,'Litre','Order Qty','/assets/Shabbos/Potato-Leek-Soup.jpg',true),
('Soups','Mushroom Barley Soup','An old-world classic — nutty barley, tender mushrooms, and herbs in a rich, earthy broth.',45.00,'Litre','Order Qty','/assets/Shabbos/Mushroom-Barley-Soup.jpg',true),
('Chicken','Shnitzlonim','Crispy, golden bites of chicken schnitzel — lightly seasoned, tender inside, and perfect for dipping or nibbling.',190.00,'1.5 Kg','Order Qty','/assets/Shabbos/Schnitzelonim.jpg',true),
('Chicken','Poppers','Juicy chicken morsels tossed in a sweet and tangy glaze — playful, flavorful, and impossible to resist.',220.00,'1.5 Kg','Order Qty','/assets/Shabbos/Poppers.jpg',true),
('Chicken','Chicken Lomein','Rustic meets East — sautéed noodles, crisp vegetables, and tender chicken in a light soy-garlic sauce.',220.00,'9x13 Pan','Order Qty','/assets/Shabbos/Chicken-Lo-Mein.jpg',true),
('Chicken','Apricot Chicken','Tender chicken glazed in a sweet-savory apricot sauce that melts into a caramelized glaze.',240.00,'9x13 Pan (6 Pieces)','Order Qty','/assets/Shabbos/apricot-chicken.jpg',true),
('Chicken','Olive Chicken','Braised with green olives, lemon, and herbs — bright Mediterranean flavors wrapped in comfort.',240.00,'9x13 Pan (6 Pieces)','Order Qty','/assets/Shabbos/Olive Chicken.jpg',true),
('Chicken','Zaatar Herbed Chicken','Marinated in za’atar, garlic, and olive oil — roasted to bring out bold, earthy Middle Eastern notes.',240.00,'9x13 Pan (6 Pieces)','Order Qty','/assets/Shabbos/zaatar-chicken.jpg',true),
('Chicken','Grilled Chicken White','Simply seasoned and flame-grilled for clean, wholesome flavor — perfect with any side.',190.00,'1.5 Kg','Order Qty','/assets/Shabbos/Grilled Chicken.jpg',true),
('Chicken','Grilled Pargiyot','Juicy dark-meat chicken grilled over open flame — smoky, tender, and infused with herbs.',385.00,'1.5 Kg','Order Qty','/assets/Shabbos/Chicken Thighs.jpg',true),
('Chicken','Chicken Shish-Kabobs','Chicken Shish-Kabobs',220.00,'9x13 Pan','Order Qty','/assets/Shabbos/Chicken Shish-Kabobs.jpg',true),
('Chicken','Spatchcock Chicken','Whole butterflied chicken roasted crisp and golden — seasoned simply, served beautifully rustic.',150.00,'Whole Chicken','Order Qty','/assets/Shabbos/spatchcock-chicken.jpg',true),
('Meat','Balsamic Glazed Brisket','Slow-braised brisket in a rich balsamic reduction — deeply caramelized with a touch of sweetness and tang.',385.00,'1.5 Kg','Order Qty','/assets/Shabbos/Balsamic Glazed Brisket.jpg',true),
('Meat','Kebobs','',300.00,'9x13 Pan','Order Qty','/assets/Shabbos/Meat Kebob.jpg',true),
('Meat','Sweet and Saucy Brisket','Melt-in-your-mouth brisket smothered in our signature sweet-savory sauce — a true family favorite.',385.00,'1.5 Kg','Order Qty','/assets/Shabbos/Sweet and Saucy Brisket.jpeg',true),
('Meat','Pulled Beef Brisket','Tender strands of beef slow-cooked until they fall apart, soaked in rich pan juices and rustic spice.',385.00,'1.5 Kg','Order Qty','/assets/Shabbos/Pulled Beef Brisket.jpg',true),
('Meat','Beer Brisket','Braised low and slow in dark beer and onions — hearty, malty, and deeply flavorful.',385.00,'1.5 Kg','Order Qty','/assets/Shabbos/Beer Brisket.jpg',true),
('Meat','Corned Beef','Classic brined cut, slow-cooked until fork-tender — perfectly seasoned and satisfyingly salty.',385.00,'1.5 Kg','Order Qty','/assets/Shabbos/Corned Beef.jpg',true),
('Meat','Bourbon Braised Brisket','A luxurious twist — infused with bourbon, brown sugar, and caramelized onions for deep, smoky richness.',385.00,'1.5 Kg','Order Qty','/assets/Shabbos/Bourbon Braised Brisket.jpg',true),
('Meat','Deli Roll','Layers of spiced deli meats rolled in golden pastry — savory, flaky, and utterly nostalgic.',100.00,'Roll','Order Qty','/assets/Shabbos/Deli Roll.jpg',true),
('Meat','Meat Cholent','Slow-simmered overnight Cholent with tender meat, barley, beans, and potatoes.',550.00,'Large Crock Pot','Order Qty','/assets/Shabbos/Chulent.jpg',true),
('Meat','Franks and Blanks','Mini hot dogs wrapped in puff pastry — a playful, crowd-pleasing favorite with a rustic twist.',225.00,'9x13 Pan','Order Qty','/assets/Shabbos/Hot Dogs In A Blanket.jpg',true),
('Sides','Garlic Soy Green Beans','Crisp green beans tossed in garlic, soy, and sesame — a simple yet vibrant side bursting with savory flavor.',80.00,'9x13 Pan','Order Qty','/assets/Shabbos/Garlic Soy Green Beans.jpg',true),
('Sides','Pastrami Green Beans','A rustic favorite — tender green beans sautéed with smoky pastrami and onions for a bold, savory twist.',130.00,'9x13 Pan','Order Qty','/assets/Shabbos/Pastrami Grean Beans.jpg',true),
('Sides','Crunchy Green Beans With Caramelized Onions','Sweet golden onions and crisp green beans meet in this homestyle dish — earthy, rustic, and deeply satisfying.',90.00,'9x13 Pan','Order Qty','/assets/Shabbos/Crunchy Green Beans With Carmalized Onions.jpg',true),
('Sides','Classic White Rice','Fluffy, perfectly steamed white rice — the timeless companion to any main course.',80.00,'9x13 Pan','Order Qty','/assets/Shabbos/Classic White Rice.jpg',true),
('Sides','Rice Pilaf','Fragrant rice cooked with sautéed onions and a touch of spice — light, buttery, and full of old-world charm.',140.00,'9x13 Pan','Order Qty','/assets/Shabbos/Rice Pilaf.jpeg',true),
('Sides','Jewel Toned Orzo','Delicate orzo pasta tossed with colorful roasted vegetables — a vibrant, Mediterranean-inspired side that dazzles the table.',140.00,'9x13 Pan','Order Qty','/assets/Shabbos/Jewel Toned Orzo.jpeg',true),
('Sides','Roasted Potatoes','Rustic wedges roasted golden with herbs, olive oil, and sea salt — crisp outside, creamy inside.',100.00,'9x13 Pan','Order Qty','/assets/Shabbos/Roasted Potatoes.jpg',true),
('Sides','Roasted Vegetable Medley','A hearty blend of seasonal vegetables roasted to bring out their natural sweetness and color — wholesome and rustic.',140.00,'9x13 Pan','Order Qty','/assets/Shabbos/Roasted Vegetable Medley.jpg',true),
('Sides','Potato Kugel','Golden, crispy edges and soft, savory center — the beloved Shabbos classic, baked just right.',100.00,'9x13 Pan','Order Qty','/assets/Shabbos/Potato Kugel.jpeg',true),
('Sides','Broccoli Kugel','Fresh broccoli baked with herbs and a creamy blend — warm, comforting, and full of homestyle flavor.',180.00,'9x13 Pan','Order Qty','/assets/Shabbos/Broccoli Kugel.jpg',true),
('Sides','Apple Kugel','Sweetly baked apples folded into a delicate noodle base — fragrant, cozy, and perfect for Shabbos dessert or side.',120.00,'9x13 Pan','Order Qty','/assets/Shabbos/Apple Kugel.jpeg',true),
('Sides','Quinoa Roasted Vegetables','Protein-rich quinoa tossed with roasted peppers, carrots, and herbs — a wholesome, rustic dish that’s both hearty and light.',140.00,'9x13 Pan','Order Qty','/assets/Shabbos/Quinoa Roasted Vegetables.jpg',true),
('Sides','Honey Harissa Carrots','Oven-roasted carrots glazed in honey and a touch of harissa — a balance of sweetness, warmth, and subtle spice.',120.00,'9x13 Pan','Order Qty','/assets/Shabbos/Honey Harissa Carrots.jpg',true),
('Sides','Sesame Noodles','Tender noodles tossed in a rich sesame-peanut dressing with hints of soy, garlic, and ginger — comforting, nutty, and irresistibly flavorful.',100.00,'9x13 Pan','Order Qty','/assets/Shabbos/Sesame Noodles.jpg',true),
('Salads','Cabbage Salad','Crisp green cabbage tossed with lemon, olive oil, and herbs — simple, bright, and refreshing.',180.00,'3 L Container','Order Qty','/assets/Shabbos/Cabbage Salad.jpg',true),
('Salads','Cesar Salad','Romaine hearts with creamy dressing, garlic croutons.',180.00,'3 L Container','Order Qty','/assets/Shabbos/Cesar Salad.jpg',true),
('Salads','Sweet Pecan Salad','Mixed greens with roasted pecans, cranberries, and citrus vinaigrette.',200.00,'3 L Container','Order Qty','/assets/Shabbos/Sweet Pecan Salad.jpg',true),
('Salads','Curried Couscous Salad','Golden couscous with curry spices, roasted vegetables, and herbs.',180.00,'3 L Container','Order Qty','/assets/Shabbos/Curried Couscous Salad.jpg',true),
('Salads','Broccoli Salad','Fresh florets with toasted seeds and creamy dressing.',220.00,'3 L Container','Order Qty','/assets/Shabbos/Broccoli Salad.png',true),
('Salads','Sushi Salad Topped with Salmon Cubes','',300.00,'3 L Container','Order Qty','/assets/Shabbos/Sushi Salad with cooked Salmon.jpg',true);
